---
title: "Preprocessing: filtering"
output: html_notebook
---

```{r setup, include = FALSE}
# set chunk option
knitr::opts_chunk$set(echo = FALSE)

# set working directory
if (!require("here")) {install.packages("here"); require("here")}
here::i_am("filtering.Rmd")

# create a folder if not exists
if (!file.exists(here("filtered"))){
  dir.create(here("filtered"))
}

# read functions
source(here("function.R"))

# read a text file for ideal performance
dt_ideal <- read.table(here("ideal.txt"))
colnames(dt_ideal) <- "Pitch"
dt_ideal$RowNr <- 1:nrow(dt_ideal)
setcolorder(dt_ideal, c(2, 1))

# create a list of data file names
lf <- list.files(here("raw_data"), pattern = "txt")

# create raw_data - merge all data files into one
raw_data <- data.table()
for (i in 1:length(lf)){
  data_i <- fread(file.path(here("raw_data"), lf[i]), header = F, sep = " ", dec = ".")
  raw_data <- rbind(raw_data, data_i)
}

# add column namesls
colnames(raw_data) <- c("NoteNr", "TimeStamp", "Pitch", "Velocity", "Key_OnOff", "Device", "SubNr", "TrialNr", "Stimuli", "Session")

# clean raw_data
raw_data$NoteNr <- as.numeric(gsub(",", "", raw_data$NoteNr))
raw_data$Session <- gsub(";", "", raw_data$Session)

# sort by SubNr, TrialNr
raw_data <- raw_data[order(raw_data$SubNr, raw_data$TrialNr),]

# raw_data without metronome
dt_all <- raw_data[Pitch != 31 & Pitch != 34]

# onset and offset for experimental session
dt_onset <- dt_all[Key_OnOff == 1 & Session == "experiment"]
dt_offset <- dt_all[Key_OnOff == 0 & Session == "experiment"]
```

# Detect erroneous trials

1) Onset

```{r onset}
dt_error_onset <- checker(dt_onset, dt_ideal)

# mark imperfect performances
dt_onset$Error <- 0
for (error in 1:nrow(dt_error_onset)){
  dt_onset[SubNr == dt_error_onset$SubNr[error] & TrialNr == dt_error_onset$TrialNr[error]]$Error <- 1
}

dt_correct_onset_1 <- dt_onset[Error == 0]
dt_correct_onset_1$RowNr <- rep(1:72, nrow(dt_correct_onset_1)/72)
setcolorder(dt_correct_onset_1, c(12, 1:11))

# export csv
fwrite(dt_correct_onset_1, file = here("filtered", "dt_correct_onset_1.txt"))

# print the result
dt_error_onset
```

2) Offset

```{r offset, echo = FALSE}
dt_error_offset <- checker(dt_offset, dt_ideal)

# mark imperfect performances
dt_offset$Error <- 0
for (error in 1:nrow(dt_error_offset)){
  dt_offset[SubNr == dt_error_offset$SubNr[error] & TrialNr == dt_error_offset$TrialNr[error]]$Error <- 1
}

dt_correct_offset_1 <- dt_offset[Error == 0]
dt_correct_offset_1$RowNr <- rep(1:72, nrow(dt_correct_offset_1)/72)
setcolorder(dt_correct_offset_1, c(12, 1:11))

# export csv
fwrite(dt_correct_offset_1, file = here("filtered", "dt_correct_offset_1.txt"))

# print the result
dt_error_offset
```

# Manual pitch removal

## Extra notes
1) Onset

```{r extra-onset, include = FALSE, eval = FALSE}
dt_error_onset$CorrectionNr <- NA

error_extra_onset <- dt_error_onset[Reason == "Extra Notes"]
dt_correct_onset_2 <- data.table()
for (row in 1:nrow(error_extra_onset)){
  current <- dt_onset[SubNr == error_extra_onset$SubNr[row] & TrialNr == error_extra_onset$TrialNr[row]]
  decision = 2 
  correction = 0 # # of correction for reporting stats
  while (decision == 2){
    print(sprintf("SubNr: %s, TrialNr: %s", unique(current$SubNr), unique(current$TrialNr)))
    print("----- First check -----")
    current <- edit(current, dt_ideal)
    print("----- Correction check -----")
    edit(current, dt_ideal)
    decision <- menu(c("y", "n", "other"), title = "Save the current data? (to continue, enter 'n')")
    if (decision == 1){
      correction = correction + 1
      error_extra_onset$CorrectionNr[row] <- correction
      dt_correct_onset_2 <- rbind(dt_correct_onset_2, current[, -c(5:6)])
    } else if (decision == 3){
      error_extra_onset$CorrectionNr[row] <- readline(prompt = "Reason?: ")
    } else if (decision == 2){
      correction = correction + 1
      print("----- Continue correction -----")
    }
  }
}

# export csv
fwrite(dt_correct_onset_2, file = here("filtered", "dt_correct_onset_2.txt"))
fwrite(error_extra_onset, file = here("filtered", "error_extra_onset.txt"))
```

```{r}
error_extra_onset <- fread(here("filtered/error_extra_onset.txt"))
error_extra_onset
```

2) Offset

```{r extra-offset, include = FALSE, eval = FALSE}
dt_error_offset$CorrectionNr <- NA

error_extra_offset <- dt_error_offset[Reason == "Extra Notes"]
dt_correct_offset_2 <- data.table()
for (row in 1:nrow(error_extra_offset)){
  current <- dt_offset[SubNr == error_extra_offset$SubNr[row] & TrialNr == error_extra_offset$TrialNr[row]]
  decision = 2 
  correction = 0 # # of correction for reporting stats
  while (decision == 2){
    print(sprintf("SubNr: %s, TrialNr: %s", unique(current$SubNr), unique(current$TrialNr)))
    print("----- First check -----")
    current <- edit(current, dt_ideal)
    print("----- Correction check -----")
    edit(current, dt_ideal)
    decision <- menu(c("y", "n", "other"), title = "Save the current data? (to continue, enter 'n')")
    if (decision == 1){
      correction = correction + 1
      error_extra_offset$CorrectionNr[row] <- correction
      dt_correct_offset_2 <- rbind(dt_correct_offset_2, current[, -c(5:6)])
    } else if (decision == 3){
      error_extra_offset$CorrectionNr[row] <- readline(prompt = "Reason?: ")
    } else if (decision == 2){
      correction = correction + 1
      print("----- Continue correction -----")
    }
  }
}

# export csv
fwrite(dt_correct_offset_2, file = here("filtered", "dt_correct_offset_2.txt"))
fwrite(error_extra_offset, file = here("filtered", "error_extra_offset.txt"))
```

```{r}
error_extra_offset <- fread(here("filtered/error_extra_offset.txt"))
error_extra_offset
```

## Missing notes
1) Onset

```{r missing-onset, include = FALSE, eval = FALSE}
error_missing_onset <- dt_error_onset[Reason == "Missing Notes"]

dt_correct_onset_3 <- data.table()
for (row in 1:nrow(error_missing_onset)){
  current <- dt_onset[SubNr == error_missing_onset$SubNr[row] & TrialNr == error_missing_onset$TrialNr[row]]
  diff <- abs(nrow(dt_ideal) - nrow(current))
  if (diff < 5){
    # insert NA row
    current <- insert_na(current, dt_ideal)
    print(sprintf("SubNr: %s, TrialNr: %s", unique(current$SubNr), unique(current$TrialNr)))
    print("----- Correction check -----")
    current <- edit(current, dt_ideal)
    decision <- menu(c("y", "other"), title = "Save the current data?")
    if (decision == 1){
      error_missing_onset$CorrectionNr[row] <- diff
      dt_correct_onset_3 <- rbind(dt_correct_onset_3, current[, -c(5:6)])
    } else if (decision == 2){
      error_missing_onset$CorrectionNr[row] <- readline(prompt = "Reason?: ")
    }
  } else {
    error_missing_onset$CorrectionNr[row] <- "Check individually"
  }
}

# export csv
fwrite(dt_correct_onset_3, file = here("filtered", "dt_correct_onset_3.txt"))
fwrite(error_missing_onset, file = here("filtered", "error_missing_onset.txt"))
```

```{r}
error_missing_onset <- fread(here("filtered/error_missing_onset.txt"))
error_missing_onset
```

2) Offset

```{r missing-offset, include = FALSE}
error_missing_offset <- dt_error_offset[Reason == "Missing Notes"]

dt_correct_offset_3 <- data.table()
for (row in 1:nrow(error_missing_offset)){
  current <- dt_offset[SubNr == error_missing_offset$SubNr[row] & TrialNr == error_missing_offset$TrialNr[row]]
  diff <- abs(nrow(dt_ideal) - nrow(current))
  if (diff < 5){
    # insert NA row
    current <- insert_na(current, dt_ideal)
    print(sprintf("SubNr: %s, TrialNr: %s", unique(current$SubNr), unique(current$TrialNr)))
    print("----- Correction check -----")
    current <- edit(current, dt_ideal)
    decision <- menu(c("y", "other"), title = "Save the current data?")
    if (decision == 1){
      error_missing_offset$CorrectionNr[row] <- diff
      dt_correct_offset_3 <- rbind(dt_correct_offset_3, current[, -c(5:6)])
    } else if (decision == 2){
      error_missing_offset$CorrectionNr[row] <- readline(prompt = "Reason?: ")
    }
  } else {
    error_missing_offset$CorrectionNr[row] <- "Check individually"
  }
}

# export csv
fwrite(dt_correct_offset_3, file = here("filtered", "dt_correct_offset_3.txt"))
fwrite(error_missing_offset, file = here("filtered", "error_missing_offset.txt"))
```

```{r}
error_missing_offset <- fread(here("filtered/error_missing_offset.txt"))
error_missing_offset
```
